const items = [
    {title: "Massacre of the Innocents", tag: ["baroque"], img: "/assets/massacre-of-the-innocents-1.jpeg"},
    {title: "St. Jerome in His Study", tag: ["baroque"], img: "/assets/Saint_Jerome_Writing-Caravaggio_(1605-6).jpg"},
    {title: "The Crowning with Thorns", tag: ["baroque"], img: "/assets/Michelangelo_Merisi,_called_Caravaggio_-_The_Crowning_with_Thorns_-_Google_Art_Project.jpg"},
    {title: "The Arnolfini Marriage", tag: ["renaissance"], img: "/assets/The_Arnolfini_portrait_(1434).jpg"},
    {title: "The Raft of the Medusa", tag: ["romanticism"], img: "/assets/JEAN_LOUIS_THÉODORE_GÉRICAULT_-_La_Balsa_de_la_Medusa_(Museo_del_Louvre,_1818-19).jpg"},
    {title: "The Night Watch", tag: ["baroque"], img: "/assets/p070wbmx.jpg"},
    {title: "Mona Lisa", tag: ["renaissance"], img: "/assets/mona-lisa-the-famous-paintings-2.jpeg"},
    {title: "Las Meninas", tag: ["baroque"], img: "/assets/Las_Meninas_(1656),_by_Velazquez.jpg"},
    {title: "Judith Slaying Holofernes", tag: ["baroque"], img: "/assets/Artemisia_Gentileschi_-_Judith_Beheading_Holofernes_-_WGA8563.jpg"},
    {title: "'The Calling of Saint Matthew", tag: ["baroque"], img: "/assets/The_Calling_of_Saint_Matthew-Caravaggo_(1599-1600).jpg"},
    {title: "The Birth of Venus", tag: ["renaissance"], img: "/assets/Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project_-_edited.jpg"},
    {title: "The School of Athens", tag: ["renaissance"], img: "/assets/The_School_of_Athens_by_Raffaello_Sanzio_da_Urbino.jpg"},
    {title: "The Creation of Adam", tag: ["renaissance"], img: "/assets/michelangelo-creation-of-adam.jpg"},
    {title: "Wanderer above the Sea of Fog", tag: ["romanticism"], img: "/assets/Caspar_David_Friedrich_-_Wanderer_above_the_Sea_of_Fog.jpeg"},
    {title: "The Nightmare", tag: ["romanticism"], img: "/assets/Henry_Fuseli_(1741–1825),_The_Nightmare,_1781.jpg"},
    {title: "The Persistence of Memory", tag: ["modern"], img: "/assets/Salvador-Dali-Persistence-of-Memory.jpg"},
    {title: "The Starry Night", tag: ["modern"], img: "/assets/Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg"},
    {title: "Blue Nude", tag: ["modern"], img: "/assets/nach-henri-matisse-blue-nude-1.jpg"},
    {title: "Les Demoiselles d'Avignon", tag: ["modern"], img: "/assets/Les_Demoiselles_d'Avignon.jpg"},
    {title: "Oath of the Horatii", tag: ["neo"], img: "/assets/Jacques-Louis_David,_Le_Serment_des_Horaces.jpg"},
    {title: "The Death of Socrates", tag: ["neo"], img: "/assets/David_-_The_Death_of_Socrates.jpg"},
    {title: "The Tennis Court Oath", tag: ["neo"], img: "/assets/the-tennis-court-oath-20th-june-1789.jpg"},
    {title: "The Apotheosis of Homer", tag: ["neo"], img: "/assets/the-apotheosis-of-homer-jean-auguste-dominique-ingres-painting-classic-art-greek-mythology-greek.jpg!Large.jpg"},
    {title: "The Emperor Napoleon", tag: ["neo"], img: "/assets/David_-_The_Emperor_Napoleon_in_his_Study_at_the_Tuileries_(second_version),_1812.jpg"},
    {title: "Composition VII", tag: ["abstract"], img: "/assets/640px-Vassily_Kandinsky,_1913_-_Composition_7.jpg"},
    {title: "Broadway Boogie Woogie", tag: ["abstract"], img: "/assets/Piet_Mondrian,_1942_-_Broadway_Boogie_Woogie.jpg"},
    {title: "No. 5, 1948", tag: ["abstract"], img: "/assets/number-5-Jackson-Pollock.jpg"},
    {title: "Black Square", tag: ["abstract"], img: "/assets/Kazimir-Malevich-Black-square-1915-Oil-on-Canvas-State-Tretyakov-Gallery.png"},
    {title: "Yellow, Red, Blue", tag: ["abstract"], img: "/assets/Wassily-Kandinsky-Yellow-Red-Blue_1001x.jpg"},
    {title: "The Conversion of Saint Paul", tag: ["baroque"], img: "/assets/1200px-The_Conversion_of_Saint_Paul-Caravaggio_(c._1600-1).jpg"},
    {title: "The Supper at Emmaus", tag: ["baroque"], img: "/assets/1200px-1602-3_Caravaggio,Supper_at_Emmaus_National_Gallery,_London.jpg"},
    {title: "The Martyrdom of Saint Sebastian", tag: ["baroque"], img: "/assets/1200px-Antonio_Pollaiuolo_003_cropframe.JPG"},
    {title: "The Triumph of Bacchus", tag: ["baroque"], img: "/assets/1200px-Velázquez_-_El_Triunfo_de_Baco_o_Los_Borrachos_(Museo_del_Prado,_1628-29).jpg"},
    {title: "The Garden of Earthly Delights", tag: ["baroque"], img: "/assets/bosch-7.jpg"},
    {title: "The Raising of Lazarus", tag: ["baroque"], img: "/assets/Rembrandt_Harmensz._van_Rijn_-_The_Raising_of_Lazarus_-_Google_Art_Project.jpg"},
    {title: "The Anatomy Lesson of Dr. Nicolaes Tulp", tag: ["baroque"], img: "/assets/Rembrandt_-_The_Anatomy_Lesson_of_Dr_Nicolaes_Tulp.jpg"},
    {title: "The Denial of Saint Peter", tag: ["baroque"], img: "/assets/The_Denial_of_Saint_Peter-Caravaggio_(1610).jpg"},
    {title: "The Allegory of Painting", tag: ["baroque"], img: "/assets/Jan_Vermeer_-_The_Art_of_Painting_-_Google_Art_Project.jpg"},
    {title: "The Third of May 1808", tag: ["romanticism"], img: "/assets/aa41e7bac50d9f9cd236599471d86fe2ce7686d4.jpg"},
    {title: "The Slave Ship", tag: ["romanticism"], img: "/assets/Slave-ship.jpg"},
    {title: "Snowstorm: Hannibal and his Army Crossing the Alps", tag: ["romanticism"], img: "/assets/Joseph_Mallord_William_Turner_081.jpg"},
    {title: "Death of Sardanapalus", tag: ["romanticism"], img: "/assets/Eugène_Delacroix_-_The_Death_of_Sardanapalus_-_WGA6173.jpg"},
    {title: "The Oxbow", tag: ["romanticism"], img: "/assets/Cole_Thomas_The_Oxbow.jpg"},
    {title: "The Fighting Temeraire", tag: ["romanticism"], img: "/assets/The_Fighting_Temeraire,_JMW_Turner,_National_Gallery.jpg"},
    {title: "The Monk by the Sea", tag: ["romanticism"], img: "/assets/Caspar_David_Friedrich_-_Der_Mönch_am_Meer_-_Google_Art_Project.jpg"},
    {title: "Evening: Landscape with an Aqueduct", tag: ["romanticism"], img: "/assets/4-evening-landscape-with-an-aqueduct-theodore-gericault.jpg"},
    {title: "The Polar Sea", tag: ["romanticism"], img: "/assets/Caspar_David_Friedrich_-_Das_Eismeer_-_Hamburger_Kunsthalle_-_02.jpg"},
    {title: "Napoleon Crossing the Alps", tag: ["neo"], img: "/assets/David_-_Napoleon_crossing_the_Alps_-_Malmaison2.jpg"},
    {title: "The Coronation of Napoleon", tag: ["neo"], img: "/assets/Jacques-Louis_David_-_The_Coronation_of_Napoleon_(1805-1807).jpg"},
    {title: "The Intervention of the Sabine Women", tag: ["neo"], img: "/assets/F0440_Louvre_JL_David_Sabines_INV3691_rwk.jpg"},
    {title: "The Death of Marat", tag: ["neo"], img: "/assets/Death_of_Marat_by_David.jpg"},
    {title: "Portrait of Madame Récamier", tag: ["neo"], img: "/assets/Madame_Récamier_by_Jacques-Louis_David.jpg"},
    {title: "The Lictors Bring to Brutus the Bodies of His Sons", tag: ["neo"], img: "/assets/David_Brutus.jpg"},
    {title: "The Sabine Women", tag: ["neo"], img: "/assets/Rape-of-the-Sabine-Women.jpg"},
    {title: "Portrait of Pope Pius VII", tag: ["neo"], img: "/assets/Jacques-Louis_David_018.jpg"},
    {title: "Napoleon at the Great St. Bernard ", tag: ["neo"], img: "/assets/Napoleon_at_the_Great_St._Bernard_-_Jacques-Louis_David_-_Google_Cultural_Institute.jpg"},
    {title: "Belisarius Begging for Alms", tag: ["neo"], img: "/assets/David_-_Belisarius.jpg"},
    {title: "The Distribution of the Eagle Standards", tag: ["neo"], img: "/assets/Jacques_Louis_David-Serment_de_l'armée_fait_à_l'Empereur_après_la_distribution_des_aigles,_5_décembre_1804.jpg"},
    {title: "The Adoration of the Magi", tag: ["renaissance"], img: "/assets/Botticelli_-_Adoration_of_the_Magi_(Zanobi_Altar)_-_Uffizi.jpg"},
    {title: "The Marriage of the Virgin", tag: ["renaissance"], img: "/assets/Raffaello_-_Spozalizio_-_Web_Gallery_of_Art.jpg"},
    {title: "The Annunciation", tag: ["renaissance"], img: "/assets/ANGELICO,_Fra_Annunciation,_1437-46_(2236990916).jpg"},
    {title: "The Entombment of Christ", tag: ["renaissance"], img: "/assets/The_Entombment_of_Christ-Caravaggio_(c.1602-3).jpg"},
    {title: "The Baptism of Christ", tag: ["renaissance"], img: "/assets/The_Baptism_of_Christ_(Verrocchio_&_Leonardo).jpg"},
    {title: "The Annunciation", tag: ["renaissance"], img: "/assets/the_Annunciation.png"},
    {title: "The Madonna of the Magnificat", tag: ["renaissance"], img: "/assets/Sandro_Botticelli_-_Madonna_del_Magnificat_-_Google_Art_Project.jpg"},
    {title: "The Assumption of the Virgin", tag: ["renaissance"], img: "/assets/Tizian_041.jpg"},
    {title: "Madonna and Child with Saint John the Baptist", tag: ["renaissance"], img: "/assets/mad_john.jpg"},
    {title: "Guernica", tag: ["modern"], img: "/assets/Guernica.png"},
    {title: "The Dance", tag: ["modern"], img: "/assets/Matissedance.jpg"},
    {title: "Nude Descending a Staircase, No. 2", tag: ["modern"], img: "/assets/Duchamp_-_Nude_Descending_a_Staircase.jpg"},
    {title: "The Red Vineyard", tag: ["modern"], img: "/assets/Red_vineyards.jpg"},
    {title: "The City Rises", tag: ["modern"], img: "/assets/The_City_Rises_by_Umberto_Boccioni_1910.jpg"},
    {title: "The Kiss", tag: ["modern"], img: "/assets/The-Kiss.jpg"},
    {title: "Woman I", tag: ["modern"], img: "/assets/restricted.jpeg"},
    {title: "White on White", tag: ["abstract"], img: "/assets/White_on_White_(Malevich,_1918).png"},
    {title: "Composition X", tag: ["abstract"], img: "/assets/kunstdruck-composition-x-neoplastizismus-moderne-malerei-piet-mondrian-kunst-a3-1-1-st.jpg"},
    {title: "Blue Poles", tag: ["abstract"], img: "/assets/blue-poles-pollock-nga.jpg"},
    {title: "Composition No. 10", tag: ["abstract"], img: "/assets/Piet_Mondriaan,_1939-1942_-_Composition_10.jpg"},
    {title: "Homage to the Square: Apparition", tag: ["abstract"], img: "/assets/61.1590_ph_web-1.jpg"},
    {title: "Number 1A", tag: ["abstract"], img: "/assets/rothko-slow-swirl.jpg"},
    {title: "Yellow and Green", tag: ["abstract"], img: "/assets/24-57.jpg"},
    {title: "Black Lines", tag: ["abstract"], img: "/assets/Frantisek-Kupka-Twisted-black-lines.jpg"},
    {title: "Cercle et Carré", tag: ["abstract"], img: "/assets/2012_0177_Delaunay_full_exhibition_page.jpg"},
    {title: "Rythme couleur", tag: ["abstract"], img: "/assets/Rythme-couleur-1076_artwork_illustration_infos_plus.jpg"},
    {title: "Red Room (Harmony in Red)", tag: ["abstract"], img: "/assets/red-room-harmony-in-red-henri-matisse.jpg"},
    {title: "Rabbit", tag: ["abstract"], img: "/assets/jeff-koons-rabbit-christies-7-684x1026.jpg"},
    {title: "Conversion on the Way to Damascus", tag: ["baroque"], img: "/assets/Conversion_on_the_Way_to_Damascus-Caravaggio_(c.1600-1).jpg"},
    {title: "The Martyrdom of Saint Sebastian", tag: ["baroque"], img: "/assets/Jusepe_de_Ribera_-_Martyrdom_of_St._Sebastian_-_M.Ob.650_-_National_Museum_in_Warsaw.jpg"},
    {title: "The Descent from the Cross", tag: ["baroque"], img: "/assets/Descent_from_the_Cross_(Rubens)_July_2015-1a.jpg"},
    {title: "Elevation of the Cross", tag: ["baroque"], img: "/assets/Elevation_of_the_Cross_(Rubens)_July_2015-1a.jpg"},
    {title: "Liberty Leading the People", tag: ["romanticism"], img: "/assets/Eugène_Delacroix_-_Le_28_Juillet._La_Liberté_guidant_le_peuple.jpg"},
    {title: "The Death of Sardanapalus", tag: ["baroque"], img: "/assets/405161.jpg"},
    {title: "Portrait of Pope Innocent X", tag: ["baroque"], img: "/assets/Retrato_del_Papa_Inocencio_X._Roma,_by_Diego_Velázquez.jpg"},
    {title: "The Four Continents", tag: ["baroque"], img: "/assets/1200px-Peter_Paul_Rubens_-_The_Four_Continents.jpg"},
    {title: "Saint Cecilia", tag: ["baroque"], img: "/assets/Simon_Vouet_-_Saint_Cecilia_-_Google_Art_Project.jpg"},
    {title: "The Triumph of Galatea", tag: ["baroque"], img: "/assets/Galatea_Raphael.jpg"},
    {title: "The Wedding at Cana", tag: ["baroque"], img: "/assets/Paolo_Veronese_008.jpg"},
    {title: "The Sacrifice of Isaac", tag: ["baroque"], img: "/assets/1280px-Sacrifice_of_Isaac-Caravaggio_(Uffizi).jpg"},
    {title: "Beheading of Saint John the Baptist", tag: ["baroque"], img: "/assets/beheading-of-saint-john-the-baptist-the-famous-pai-2.jpeg"},
    {title: "The Tempest", tag: ["baroque"], img: "/assets/1200px-Giorgione_019.jpg"},
    
];

export {items};